name: book_luck_app_demo
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  flutter_svg: ^2.0.7 # Check for the latest version on pub.dev
  cupertino_icons: ^1.0.8
  table_calendar: ^3.2.0
  lottie: ^3.3.1
  image_gallery_saver_plus: ^4.0.1
  permission_handler: ^12.0.1
  device_info_plus: ^9.0.2
  share_plus: ^10.0.2
  path_provider: ^2.1.5
  fl_chart: 0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"

  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/images/
    - assets/lottie/

  fonts:
    - family: DOSIyagiBoldface
      fonts:
        - asset: assets/fonts/DOSIyagiBoldface.ttf
    - family: MabinogiClassic
      fonts:
        - asset: assets/fonts/MabinogiClassic.ttf

    - family: SUITVariable
      fonts:
        - asset: assets/fonts/SUIT-Variable.ttf

    - family: MyPageIcon
      fonts:
        - asset: assets/fonts/MyPageIcon.ttf

    - family: HomeIcon
      fonts:
        - asset: assets/fonts/HomeIcon.ttf

    - family: FeedIcon
      fonts:
        - asset: assets/fonts/FeedIcon.ttf

    - family: BookshelfIcon
      fonts:
        - asset: assets/fonts/BookshelfIcon.ttf


  uses-material-design: true
